#!/bin/sh

base=$(dirname `readlink -f $0`)

os=`uname|tr '[A-Z]' '[a-z]'`
arch=`arch`

if [ "$os" = "darwin" ]; then
	os="mac"
fi

if [ "$arch" = "x86_64" ]; then
	arch="x64"
fi

$base/product/$os/$arch/quark $@
